import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 3,
  tables: [
    tableSchema({
      name: 'ocurrences_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'ocurrences',
      columns: [
        { name: 'address', type: 'string' },
        { name: 'district', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'obs', type: 'string' },
        { name: 'image_name', type: 'string' },
        { name: 'ocurrence_type_id', type: 'number' },
        { name: 'point_id', type: 'number' },
        { name: 'point_tag', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'members',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'routes',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'team_name', type: 'string' },
        { name: 'obs', type: 'string' },
        { name: 'date', type: 'string' },
        { name: 'status_description', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'solutions',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'services_orders',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'ocurrence_type_description', type: 'string' },
        { name: 'ocurrence_origin_descripton', type: 'string' },
        { name: 'address', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'image_url', type: 'string' },
        { name: 'date', type: 'string' },
        { name: 'obs', type: 'string' },
        { name: 'obs_os', type: 'string' },
        { name: 'solution_id', type: 'number' },
        // { name: 'member_id', type: 'number' },
        { name: 'status_id', type: 'number' },
        { name: 'sent', type: 'number' },
        // { name: 'points_amount', type: 'number' },
        { name: 'protestant', type: 'string' },
        { name: 'protestant_phone', type: 'string' },
        { name: 'image_name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'requisitions',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'requisition_id', type: 'number' },
        { name: 'product_id', type: 'number' },
        { name: 'product_name', type: 'string' },
        { name: 'requisition_amount', type: 'number' },
        { name: 'route_amount', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'services_orders_materials',
      columns: [
        { name: 'route_id', type: 'number' },
        { name: 'service_order_id', type: 'number' },
        { name: 'product_name', type: 'string' },
        { name: 'product_id', type: 'number' },
        { name: 'amount', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'posts_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reactors_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'reactors_powers',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'arms_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'lights_fixtures_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'lamps_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'lamps_powers',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'perimeters_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'places_types',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'points_ips',
      columns: [
        { name: 'tag', type: 'string' },
        { name: 'light_fixture_amount', type: 'number' },
        { name: 'obs', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'image_name', type: 'string' },
        { name: 'post_type_id', type: 'number' },
        { name: 'reactor_type_id', type: 'number' },
        { name: 'reactor_power_id', type: 'number' },
        { name: 'arm_type_id', type: 'number' },
        { name: 'light_fixture_type_id', type: 'number' },
        { name: 'lamp_type_id', type: 'number' },
        { name: 'lamp_power_id', type: 'number' },
        { name: 'perimeter_type_id', type: 'number' },
        { name: 'place_type_id', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'mappings',
      columns: [
        { name: 'route_id', type: 'number' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'status_description', type: 'string' },
        { name: 'team_name', type: 'string' },
        { name: 'obs', type: 'string' },
        { name: 'vehicle_name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds_addresses',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'address', type: 'string' },
        { name: 'round_id', type: 'number' },
        { name: 'status_id', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds_requisitions',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'requisition_id', type: 'number' },
        { name: 'product_id', type: 'number' },
        { name: 'product_name', type: 'string' },
        { name: 'requisition_amount', type: 'number' },
        { name: 'round_amount', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds_notifications',
      columns: [
        { name: 'address', type: 'string' },
        { name: 'district', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'latitude', type: 'number' },
        { name: 'longitude', type: 'number' },
        { name: 'obs', type: 'string' },
        { name: 'image_name', type: 'string' },
        { name: 'notification_type_id', type: 'number' },
        { name: 'notification_status_id', type: 'number' },
        { name: 'member_id', type: 'number' },
        { name: 'solution_id', type: 'number' },
        { name: 'point_id', type: 'number' },
        { name: 'point_tag', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds_materials',
      columns: [
        { name: 'product_id', type: 'number' },
        { name: 'round_id', type: 'number' },
        { name: 'amount', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rounds_members',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'name', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'requisitions_completed',
      columns: [
        { name: 'original_id', type: 'number' },
        { name: 'route_id', type: 'number' },
        { name: 'open_date', type: 'string' },
        { name: 'closed_date', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'requisitions_completed_items',
      columns: [
        { name: 'requisition_completed_id', type: 'number' },
        { name: 'product_id', type: 'number' },
        { name: 'product_name', type: 'string' },
        { name: 'original_quantity', type: 'number' },
        { name: 'route_quantity', type: 'number' },
        { name: 'quantity', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
